%var=rand(Nx,Ny,Nz);
var=Ex.^2+Ey.^2+Ez.^2;
var=Qex.^2+Qey.^2+Qez.^2;
%[x,y,z]=ndgrid(0:dx:Lx,0:dy:Ly,0:dz:Lz);
%var=exp(-(x-Lx/2).^2-(y-Ly/2).^2-(z-Lz/2).^2);
%var=divS;
bbb=var(:,:,:).*hamming(Nx);
bbb=bbb(:,:,:).*hamming(Ny)';
soglia=AAz(:,:,round(Nz/2))./max(AAz(:));
s_0=.5;c=.1;
st=.5*(1+tanh((soglia-s_0)./c^2));
plot(st,'.')
bbb=bbb.*st;
close all
figure(1)
imagesc(bbb(:,:,30))
bbb_fft=fftn(bbb);
figure(2)
imagesc(log(fftshift(squeeze(abs(mean(bbb_fft,3))))'))
xlabel('k_x')
ylabel('k_y')
figure(3)
semilogy(fftshift(squeeze(abs(mean(bbb_fft,3))))','.')
figure(4)
P1=squeeze(mean(bbb_fft,3));
nx=floor(Nx/2);
ny=floor(Ny/2);
P1=P1(1:nx+1,1:ny+1);
fx=1/dx*(0:nx)/Nx;
fy=1/dy*(0:ny)/Ny;
imagesc(fx,fy,log(abs(P1))')
xlabel('k_xd_i')
ylabel('k_yd_i')
figure(5)
[fxc,fyc]=ndgrid(fx,fy);
[fr, fth]=ndgrid(0:pi/10:2*pi,0:pi/10:pi/2);
P1r=griddata(fxc,fyc,abs(P1),fr.*cos(fth),fr.*sin(fth));
semilogy(fr',P1r',mean(fr'),mean(P1r'),'*')
xlabel('kd_i')