#!/bin/sh
if test $# -lt 1
then
  echo '
  To build, in the iPic3D directory you can use:
  
    rm -rf build # if necessary
    mkdir build
    cd build
    cmake ..
    make # or "make -j" to compile in parallel
  
  To run the code you can use
  
    mkdir data
    mpiexec.hydra -n 4 -env OMP_NUM_THREADS=1 exec/iPic3D ../inputfiles/GEM.inp
  
  where 4 = XLEN times YLEN times ZLEN (defined in GEM.inp).
  
  Available subcommands:

    ipic help ctags
    ipic help mic
'
  exit
fi
DIRNAME=`dirname $0`
APPENDIX="$1"
shift
exec "${DIRNAME}/ipic-help-${APPENDIX}" "$@"
