#!/bin/sh
#if test $# -lt 1
#then
  echo '
  See "ipic help".  Modifications are as follows.

  To run on the Xeon host processor, use something like:
  
    mpiexec.hydra -n 8 -env OMP_NUM_THREADS=4 exec/iPic3D ../inputfiles/GEM.inp
  
  where 8 = XLEN times YLEN times ZLEN.
  
  If you want to cross-compile for the MIC, then the instructions are
  different:
  
      mkdir build.phi
      cd build.phi
      cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/cmake_template.cmake.XeonPhi
      make -j
  
  And to run you use, e.g.:
  
    mkdir data
    mpiexec.hydra -host knc2-mic0 -n 50 -env OMP_NUM_THREADS=4 exec/iPic3D ../inputfiles/GEM.inp
  
  where 50 = XLEN times YLEN times ZLEN.
'

